# generated by datamodel-codegen:
#   filename:  signal-cli-rest-api.json

from __future__ import annotations

from pydantic import BaseModel

from signalbot._generated.receive.message_envelope import MessageEnvelope


class Message(BaseModel):
    account: str
    envelope: MessageEnvelope
