# generated by datamodel-codegen:
#   filename:  signal-cli-rest-api.json

from __future__ import annotations

from enum import StrEnum


class SendMessages(StrEnum):
    ONLY_ADMINS = "only-admins"
    EVERY_MEMBER = "every-member"
