# generated by datamodel-codegen:
#   filename:  signal-cli-rest-api.json

from __future__ import annotations

from enum import StrEnum


class TextMode(StrEnum):
    NORMAL = "normal"
    STYLED = "styled"
