import importlib.metadata

from signalbot.attachments import (
    Attachment,
    DeleteAttachmentError,
    DownloadAttachmentError,
    PydanticPath,
)
from signalbot.auth import Authentication, BasicAuthentication, BearerAuthentication
from signalbot.bot import (
    MIN_SIGNAL_CLI_REST_API_VERSION,
    SignalBot,
)
from signalbot.bot_config import (
    BasicAuthConfig,
    BearerAuthConfig,
    Config,
    InMemoryConfig,
    RedisConfig,
    SQLiteConfig,
    load_config,
)
from signalbot.client import ConnectionMode
from signalbot.contacts import UpdateContact, UpdateContactError
from signalbot.context import (
    Context,
    DataMessageContext,
    GroupUpdateContext,
    MessageT,
    ReactionContext,
    ReadyContext,
    RemoteDeleteContext,
    TypingContext,
)
from signalbot.errors import SignalAPIError, SignalBotError
from signalbot.events import GroupInfo
from signalbot.general import About, AboutError, HealthCheckError
from signalbot.groups import (
    AddMembers,
    EditGroup,
    GetGroupsError,
    GroupEntry,
    GroupLink,
    GroupPermissions,
    GroupRegistry,
    GroupUpdate,
    GroupUpdateInfo,
    SendMessages,
    UpdateGroup,
    UpdateGroupError,
)
from signalbot.handlers import (
    AnyHandler,
    DataMessageHandler,
    GroupUpdateHandler,
    HandlerList,
    ReactionHandler,
    ReadyHandler,
    RemoteDeleteHandler,
    TypingHandler,
    reaction_triggered,
    regex_triggered,
    text_triggered,
)
from signalbot.logger import LOGGER_NAME
from signalbot.messages import (
    BaseSendMessage,
    DataMessage,
    EditMessage,
    LinkPreview,
    Mention,
    MessageMention,
    Preview,
    Quote,
    QuotedAttachment,
    ReceivedMessage,
    ReceiveError,
    RemoteDelete,
    RemoteDeleteError,
    SendError,
    SendMessage,
    SendMessageMultiple,
    SentMessage,
    StartTypingError,
    Sticker,
    StopTypingError,
    TextMode,
    TextStyle,
    TypingAction,
    TypingError,
    TypingMessage,
    UnknownMessageFormatError,
    parse,
)
from signalbot.polls import CreatedPoll, CreatePoll, CreatePollError
from signalbot.reactions import Reaction, SendReactionError
from signalbot.receipts import ReceiptType, SendReceiptError
from signalbot.storage import (
    RedisStorage,
    SQLiteStorage,
    StorageBackend,
    StorageError,
    StorageOperation,
)
from signalbot.test_utils import (
    ChatTestCase,
    DummyHandler,
    GetAllMock,
    ReactMock,
    ReceiveMock,
    SendMock,
    mock_chat,
)

__all__ = [
    "LOGGER_NAME",
    "MIN_SIGNAL_CLI_REST_API_VERSION",
    "About",
    "AboutError",
    "AddMembers",
    "AnyHandler",
    "Attachment",
    "Authentication",
    "BaseSendMessage",
    "BasicAuthConfig",
    "BasicAuthentication",
    "BearerAuthConfig",
    "BearerAuthentication",
    "ChatTestCase",
    "Config",
    "ConnectionMode",
    "Context",
    "CreatePoll",
    "CreatePollError",
    "CreatedPoll",
    "DataMessage",
    "DataMessageContext",
    "DataMessageHandler",
    "DeleteAttachmentError",
    "DownloadAttachmentError",
    "DummyHandler",
    "EditGroup",
    "EditMessage",
    "GetAllMock",
    "GetGroupsError",
    "GroupEntry",
    "GroupInfo",
    "GroupLink",
    "GroupPermissions",
    "GroupRegistry",
    "GroupUpdate",
    "GroupUpdateContext",
    "GroupUpdateHandler",
    "GroupUpdateInfo",
    "HandlerList",
    "HealthCheckError",
    "InMemoryConfig",
    "LinkPreview",
    "Mention",
    "MessageMention",
    "MessageT",
    "Preview",
    "PydanticPath",
    "Quote",
    "QuotedAttachment",
    "ReactMock",
    "Reaction",
    "ReactionContext",
    "ReactionHandler",
    "ReadyContext",
    "ReadyHandler",
    "ReceiptType",
    "ReceiveError",
    "ReceiveMock",
    "ReceivedMessage",
    "RedisConfig",
    "RedisStorage",
    "RemoteDelete",
    "RemoteDeleteContext",
    "RemoteDeleteError",
    "RemoteDeleteHandler",
    "SQLiteConfig",
    "SQLiteStorage",
    "SendError",
    "SendMessage",
    "SendMessageMultiple",
    "SendMessages",
    "SendMock",
    "SendReactionError",
    "SendReceiptError",
    "SentMessage",
    "SignalAPIError",
    "SignalBot",
    "SignalBotError",
    "StartTypingError",
    "Sticker",
    "StopTypingError",
    "StorageBackend",
    "StorageError",
    "StorageOperation",
    "TextMode",
    "TextStyle",
    "TypingAction",
    "TypingContext",
    "TypingError",
    "TypingHandler",
    "TypingMessage",
    "UnknownMessageFormatError",
    "UpdateContact",
    "UpdateContactError",
    "UpdateGroup",
    "UpdateGroupError",
    "load_config",
    "mock_chat",
    "parse",
    "reaction_triggered",
    "regex_triggered",
    "text_triggered",
]

try:
    __version__ = importlib.metadata.version(__name__)
except importlib.metadata.PackageNotFoundError:
    __version__ = "0.0.0"
