# generated by datamodel-codegen:
#   filename:  signal-cli-rest-api.json

from __future__ import annotations

from pydantic import BaseModel, Field

from .attachment import Attachment


class ContactAvatar(BaseModel):
    attachment: Attachment | None = None
    is_profile: bool = Field(..., alias="isProfile")
