# generated by datamodel-codegen:
#   filename:  signal-cli-rest-api.json

from __future__ import annotations

from pydantic import BaseModel, Field


class HangupMessage(BaseModel):
    device_id: int = Field(..., alias="deviceId")
    id: int | None = None
    type: str | None = None
