# generated by datamodel-codegen:
#   filename:  signal-cli-rest-api.json

from __future__ import annotations

from pydantic import BaseModel, Field


class PollCreate(BaseModel):
    allow_multiple: bool = Field(..., alias="allowMultiple")
    options: list[str] | None = None
    question: str | None = None
