# generated by datamodel-codegen:
#   filename:  signal-cli-rest-api.json

from __future__ import annotations

from pydantic import BaseModel

from .contact_address import ContactAddress
from .contact_avatar import ContactAvatar
from .contact_email import ContactEmail
from .contact_name import ContactName
from .contact_phone import ContactPhone


class SharedContact(BaseModel):
    address: list[ContactAddress] | None = None
    avatar: ContactAvatar | None = None
    email: list[ContactEmail] | None = None
    name: ContactName | None = None
    organization: str | None = None
    phone: list[ContactPhone] | None = None
