# generated by datamodel-codegen:
#   filename:  signal-cli-rest-api.json

from __future__ import annotations

from pydantic import BaseModel, Field

from .attachment import Attachment
from .text_attachment import TextAttachment


class StoryMessage(BaseModel):
    allows_replies: bool = Field(..., alias="allowsReplies")
    file_attachment: Attachment | None = Field(default=None, alias="fileAttachment")
    group_id: str | None = Field(default=None, alias="groupId")
    text_attachment: TextAttachment | None = Field(default=None, alias="textAttachment")
