# generated by datamodel-codegen:
#   filename:  signal-cli-rest-api.json

from __future__ import annotations

from pydantic import BaseModel, Field

from .sync_data_message import SyncDataMessage
from .sync_read_message import SyncReadMessage
from .sync_story_message import SyncStoryMessage
from .type import TypeModel


class SyncMessage(BaseModel):
    blocked_group_ids: list[str] | None = Field(default=None, alias="blockedGroupIds")
    blocked_numbers: list[str] | None = Field(default=None, alias="blockedNumbers")
    read_messages: list[SyncReadMessage] | None = Field(
        default=None, alias="readMessages"
    )
    sent_message: SyncDataMessage | None = Field(default=None, alias="sentMessage")
    sent_story_message: SyncStoryMessage | None = Field(
        default=None, alias="sentStoryMessage"
    )
    type: TypeModel | None = None
