# generated by datamodel-codegen:
#   filename:  signal-cli-rest-api.json

from __future__ import annotations

from pydantic import BaseModel, Field

from .attachment import Attachment
from .text_attachment import TextAttachment


class SyncStoryMessage(BaseModel):
    allows_replies: bool | None = Field(default=None, alias="allowsReplies")
    destination_number: str | None = Field(default=None, alias="destinationNumber")
    destination_uuid: str | None = Field(default=None, alias="destinationUuid")
    file_attachment: Attachment | None = Field(default=None, alias="fileAttachment")
    group_id: str | None = Field(default=None, alias="groupId")
    text_attachment: TextAttachment | None = Field(default=None, alias="textAttachment")
